version: "3.9"
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:management
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit