version: "3.9"
services:
  cloud-service-registry:
    image: "cloud-service-registry:0.0.1"
    ports:
      - "8761:8761"
  cloud-config:
    image: "cloud-config:0.0.1"
    environment:
      - GIT_URI=${GIT_URI}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PASSWORD=${GIT_PASSWORD}
      - KAFKA_BROKERS=kafka
      - KAFKA_DEFAULT_BROKER_PORT=9092
      - KAFKA_AUTO_CREATE_TOPIC=true
    depends_on:
      - kafka
  cloud-explorer:
    image: "cloud-explorer:0.0.1"
    ports:
      - "8001:8080"
    environment:
      - CONFIG_SERVER=http://cloud-config:8080
      - SPRING_PROFILES_ACTIVE=cloud,test
    depends_on:
      - kafka
      - cloud-config
      - cloud-service-registry
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
