spring:
  application:
    name: cloud-explorer
  config:
    import: configserver:${CONFIG_SERVER}
  cloud:
    config:
      fail-fast: true

configuration:
  projectName: Spring Boot
management:
  endpoints:
    web:
      exposure:
        include: health, configprops, refresh, busrefresh, busenv
