management:
  endpoints:
    web:
      exposure:
        include: health, configprops, refresh, busrefresh, busenv, info

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

