spring.cloud:
  config:
    server:
      git:
        uri: ${GIT_URI}
        username: ${GIT_USERNAME}
        password: ${GIT_PASSWORD}

spring.cloud.stream:
  kafka:
    binder:
      brokers: ${KAFKA_BROKERS}
      defaultBrokerPort: ${KAFKA_DEFAULT_BROKER_PORT}
      autoCreateTopics: ${KAFKA_AUTO_CREATE_TOPIC:false}
