spring.cloud:
  config:
    server:
      git:
        uri: ${GIT_URI}
        username: ${GIT_USERNAME}
        password: ${GIT_PASSWORD}

spring.rabbitmq:
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}

